import type { Metadata } from 'next';
import Script from 'next/script';

import 'bootstrap/dist/css/bootstrap.css';
import '../libs/prism/prism.min.css';
import '../libs/FreezeUI/freeze-ui.min.css';

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

export const metadata: Metadata = {
  icons: {
    icon: `${basePath}/favicon.ico`,
  },
  title: 'Firma Digital - Jacobitus Total',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script src={`${basePath}/assets/vendor/FreezeUI/freeze-ui.min.js`} strategy="beforeInteractive" />
        <Script src={`${basePath}/assets/vendor/prism/prism.min.js`} strategy="beforeInteractive" />
      </head>
      <body className='bg-dark'>{children}</body>
    </html>
  )
}
